apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-qingcai-tls
spec:
  secretName: k8s-qingcai
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: qingcai.com
  dnsNames:
    - qingcai.com
    - www.qingcai.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - qingcai.com
          - www.qingcai.com
